openapi: 3.0.0
info:
  title: API de Carrito de Compras
  version: 1.0.0
paths:
  /api/cart:
    post:
      summary: Crear un nuevo carrito
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              example:
                {
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff",
                      "quantity": 1
                    }
                  ]
                }
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "message": "success",
                  "result": {
                    "id": "64c3307aeefd1ce9078174e8",
                    "products": [
                      {
                        "id": "64c3307aeefd1ce9078174e9",
                        "quantity": 1
                      }
                    ]
                  }
                }
        "500":
          description: Internal Error Server
  /api/cart/{id}:
    get:
      summary: Obtener información de un carrito por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64c3307aeefd1ce9078174e8",
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                  ]
                }
    put:
      summary: Actualizar información de un carrito
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              example:
                {
                  "products": [
                    {
                      "id": "644ab97a97f88b1c6448a044",
                      "quantity": 1
                    },
                    {
                      "id": "643c0c0801d8fb15b03506fa",
                      "quantity": 120
                    }
                  ]
                }
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64c3307aeefd1ce9078174e8"
                }
    delete:
      summary: Eliminar un carrito
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64c3307aeefd1ce9078174e8"
                }
  /api/cart/{id}/product/{pid}:
    post:
      summary: Agregar un producto a un carrito
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64599c00ceedae0798357817",
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff",
                      "quantity": 1
                    },
                    {
                      "id": "644ab97197f88b1c6448a040",
                      "quantity": 10
                    },
                    {
                      "id": "644ab97a97f88b1c6448a044",
                      "quantity": 2
                    }
                  ]
                }
    put:
      summary: Actualizar información de un producto en un carrito
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              example:
                {
                  "quantity": 1
                }
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64c40f8b80596c3222576e3e",
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff",
                      "quantity": 1
                    }
                  ]
                }
    delete:
      summary: Eliminar un producto de un carrito
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "id": "64c40dd999ea680cf139ad62",
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff"
                    }
                  ]
                }
components:
  schemas:
    Carts:
      type: object
      properties:
        id:
          type: ObjectId
        products:
          type: array
          items:
            $ref: '#/components/schemas/Products'