openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Obtener lista de productos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Página de resultados
        - in: query
          name: limit
          schema:
            type: integer
          description: Límite de resultados por página
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#components/schemas/Products'
              example:
                {
                  "status": "success",
                  "products": [
                    {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                  ],
                  "totalDocs": 8,
                  "limit": 10,
                  "totalPages": 1,
                  "page": 1,
                  "pagingCounter": 1,
                  "hasPrevPage": false,
                  "hasNextPage": false,
                  "prevPage": null,
                  "nextPage": null
                }
        "500":
          description: Internal Error Server
    post:
      summary: Create Product
      tags:
        - Products
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              example:
                {
                  "id": "643c0c7701d8fb15b03506ff",
                  "title": "producto de prueba",
                  "description": "producto deprueba",
                  "code": "avpjgs",
                  "price": 50,
                  "status": true,
                  "stock": 1,
                  "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                }
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#components/schemas/Products'
              example:
                {
                  "status": "success",
                  "products": {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                }
        "500":
          description: Internal Error Server
  /api/products/{id}:
    get:
      summary: Obtener información de un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "products": {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                }

    put:
      summary: Actualizar información de un producto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
              example:
                {
                  "status": "success",
                  "products": {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                }
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "products": {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                }

    delete:
      summary: Eliminar un producto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              example:
                {
                  "status": "success",
                  "products": {
                      "id": "643c0c7701d8fb15b03506ff",
                      "title": "producto de prueba",
                      "description": "producto deprueba",
                      "code": "avpjgs",
                      "price": 50,
                      "status": true,
                      "stock": 1,
                      "thumbnail": "https://www.taylorguitars.com/sites/default/files/styles/product_hero/…"
                    }
                }

components:
  schemas:
    Products:
      type: object
      properties:
        id:
          type: ObjectId
        title:
          type: String
          required: true
        description:
          type: String
          required: true
        code:
          type: String
          required: true
          unique: true
        price:
          type: Number
          required: true
        status:
          type: Boolean
          default: true
        stock:
          type: Number
          required: true
        thumbnail:
          type: string
