version: '3.6'

services:  
  node:
    container_name: ecomerce_app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - codernet
  db: 
    container_name: ecomerce_db
    restart: always
    image: bitnami/mongodb:4.2
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=4844400
      - MONGODB_USERNAME=Naeriix
      - MONGODB_PASSWORD=4844400
      - MONGODB_DATABASE=ecomerce
    networks:
      - codernet
  mail:
    container_name: ecomerce_mail
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
     - codernet

networks:
  codernet:
    driver: "bridge"